spring:
  flyway:
    locations: classpath:db/migration,classpath:db/seed
  jpa:
    show-sql: true

logging:
  level:
    com.guiderun.server: INFO
    org.springframework.orm.jpa: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
